# Generated by Django 4.1.6 on 2023-02-14 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_rename_date_follow_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="follower",
        ),
        migrations.RemoveField(
            model_name="follow",
            name="following",
        ),
        migrations.AddField(
            model_name="follow",
            name="user1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="follow",
            name="user2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
